In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print('x = ', x)

x =  [1 2 3 4 5]


In [3]:
print('x has dimensions:', x.shape)

x has dimensions: (5,)


In [4]:
print('x is an object of type:', type(x))

x is an object of type: <class 'numpy.ndarray'>


In [5]:
print('The elements in x are of type:', x.dtype)

The elements in x are of type: int32


In [6]:
x.dtype

dtype('int32')

In [7]:
x = np.array(['Hello', 'World'])

x

array(['Hello', 'World'], dtype='<U5')

In [8]:
print('x has dimensions:', x.shape)

x has dimensions: (2,)


In [9]:
print('x is an object of type:', type(x))


x is an object of type: <class 'numpy.ndarray'>


In [10]:
print('The elements in x are of type:', x.dtype)

The elements in x are of type: <U5


In [11]:
x = np.array([1, 2, 'World'])

print('x = ', x)

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


In [12]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print('Y = \n', Y)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [13]:
x = np.array([1,2,3])

y = np.array([1.0,2.0,3.0])

z = np.array([1, 2.5, 4])

print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [14]:
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(x)
print('The elements in x are of type:', x.dtype)

[1 2 3 4 5]
The elements in x are of type: int64


In [15]:
x = np.array([1, 2, 3, 4, 5])

np.save('my_array', x)

In [16]:
#to load the array that has been saved
y = np.load('my_array.npy')

print(y)

print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

[1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


# Using Built in Functions 

In [17]:
X = np.zeros((3,4))

print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [19]:
X = np.ones((3,2))
print( X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [20]:
X = np.full((2,3), 5) 

print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  

[[5 5 5]
 [5 5 5]]
X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In [21]:
#For Identity Matrix 
X = np.eye(5)

print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [22]:
X = np.diag([10,20,30,50])

print('X = \n', X)

X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [23]:
x = np.arange(10)
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [0 1 2 3 4 5 6 7 8 9]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [24]:
x = np.arange(4,10)

print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x =  [4 5 6 7 8 9]
x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [25]:
x = np.arange(1,14,3)

print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x =  [ 1  4  7 10 13]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [26]:
x = np.linspace(0,25,10)

print('x = \n', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [27]:
x = np.arange(20)

print('Original x = ', x)

x = np.reshape(x, (4,5))

print('Reshaped x = \n', x)

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [28]:
Y = np.arange(20).reshape(4, 5)

print('Y = \n', Y)
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [29]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]
X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [30]:
X = np.random.random((3,3))

print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X = 
 [[0.6063296  0.18741837 0.26077821]
 [0.16404334 0.20099265 0.21641585]
 [0.0318487  0.89578192 0.08645545]]
X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [31]:
X = np.random.randint(4,15,size=(3,2))

print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[14 10]
 [13 11]
 [ 5  6]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In [32]:
X = np.random.normal(0, 0.1, size=(1000,1000))

print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X = 
 [[-0.11640473 -0.11935966  0.04893302 ... -0.02358499  0.08748147
   0.16811592]
 [ 0.0651578   0.04962531 -0.08775428 ... -0.02441297  0.07031362
   0.02709855]
 [-0.02891217 -0.0031047   0.05656836 ...  0.05036372 -0.07935569
  -0.06938962]
 ...
 [-0.00494835 -0.03886392 -0.02519195 ...  0.0641888   0.23863534
  -0.09886107]
 [-0.08704159 -0.06892378 -0.34495302 ... -0.11872381  0.03437895
  -0.18725774]
 [ 0.00250496  0.00994434 -0.00906837 ...  0.07279077 -0.01088629
   0.01442208]]
X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 7.452062201997948e-05
The maximum value in X is: 0.48420206253758524
The minimum value in X is: -0.5132384023402051
X has 500161 negative numbers
X has 499839 positive numbers


# Accessing ,Deleting and Inserting Elements into ndarrays

In [33]:
x = np.array([1, 2, 3, 4, 5])

print(x)

print(x[0]) 
print(x[1])
print(x[4])

print(x[-5])
print(x[-4])
print(x[-1])

[1 2 3 4 5]
1
2
5
1
2
5


In [42]:
x = np.array([1, 2, 3, 4, 5])

print('Original:\n x = ', x)
x[3] = 20
print('Modified:\n x = ', x)


Original:
 x =  [1 2 3 4 5]
Modified:
 x =  [ 1  2  3 20  5]


In [43]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('X = \n', X)

print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [44]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('Original:\n X = \n', X)
X[0,0] = 20
print('Modified:\n X = \n', X)

Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [45]:
x = np.array([1, 2, 3, 4, 5])

Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('Original x = ', x)

x = np.delete(x, [0,4])

print('Modified x = ', x)

print('Original Y = \n', Y)

w = np.delete(Y, 0, axis=0)

v = np.delete(Y, [0,2], axis=1)

print('w = \n', w)

print('v = \n', v)

Original x =  [1 2 3 4 5]
Modified x =  [2 3 4]
Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
w = 
 [[4 5 6]
 [7 8 9]]
v = 
 [[2]
 [5]
 [8]]


In [39]:
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


In [46]:
x = np.array([1, 2, 5, 6, 7])

Y = np.array([[1,2,3],[7,8,9]])

print('Original x = ', x)

x = np.insert(x,2,[3,4])

print('x = ', x)

print('Original Y = \n', Y)

w = np.insert(Y,1,[4,5,6],axis=0)

v = np.insert(Y,1,5, axis=1)

print('w = \n', w)

print('v = \n', v)

Original x =  [1 2 5 6 7]
x =  [1 2 3 4 5 6 7]
Original Y = 
 [[1 2 3]
 [7 8 9]]
w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
v = 
 [[1 5 2 3]
 [7 5 8 9]]


In [47]:
x = np.array([1,2])

Y = np.array([[3,4],[5,6]])

print('x = ', x)

print('Y = \n', Y)

z = np.vstack((x,Y))

w = np.hstack((Y,x.reshape(2,1)))

print('z = \n', z)

print('w = \n', w)

x =  [1 2]
Y = 
 [[3 4]
 [5 6]]
z = 
 [[1 2]
 [3 4]
 [5 6]]
w = 
 [[3 4 1]
 [5 6 2]]


# Slicing

In [49]:
X = np.arange(20).reshape(4, 5)

print('X = \n', X)

Z = X[1:4,2:5]

print('Z = \n', Z)

W = X[1:,2:5]

print('W = \n', W)

Y = X[:3,2:5]

print('Y = \n', Y)

v = X[2,:]

print('v = ', v)

q = X[:,2]

print('q = ', q)

R = X[:,2:3]

print('R = \n', R)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
v =  [10 11 12 13 14]
q =  [ 2  7 12 17]
R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


In [50]:
X = np.arange(20).reshape(4, 5)

print('X = \n', X)

Z = X[1:4,2:5]

print('Z = \n', Z)

Z[2,2] = 555

print('X = \n', X)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


In [52]:
X = np.arange(20).reshape(4, 5)

Z = np.copy(X[1:4,2:5])

W = X[1:4,2:5].copy()

Z[2,2] = 555

W[2,2] = 444

print('X = \n', X)

print('Z = \n', Z)

print('W = \n', W)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]
W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


In [53]:
X = np.arange(20).reshape(4, 5)

indices = np.array([1,3])

print('X = \n', X)

print('indices = ', indices)

Y = X[indices,:]

Z = X[:, indices]

print('Y = \n', Y)

print('Z = \n', Z)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
indices =  [1 3]
Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]
Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [54]:
X = np.arange(25).reshape(5, 5)

print('X = \n', X)

print('z =', np.diag(X))

print('y =', np.diag(X, k=1))

print('w = ', np.diag(X, k=-1))

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
z = [ 0  6 12 18 24]
y = [ 1  7 13 19]
w =  [ 5 11 17 23]


In [55]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

print('X = \n', X)

print('The unique elements in X are:',np.unique(X))

X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]
The unique elements in X are: [1 2 3 5 8]


# Boolean Indexing ,Sorting, Set Operations

In [56]:
X = np.arange(25).reshape(5, 5)

print('Original X = \n', X)

print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

X[(X > 10) & (X < 17)] = -1

print('X = \n', X)


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]
X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [57]:
x = np.array([1,2,3,4,5])

y = np.array([6,7,2,8,4])

print('x = ', x)

print('y = ', y)

print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

x =  [1 2 3 4 5]
y =  [6 7 2 8 4]
The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [58]:
x = np.random.randint(1,11,size=(10,))

print('Original x = ', x)

print('Sorted x (out of place):', np.sort(x))

print('x after sorting:', x)

Original x =  [9 9 2 9 6 2 3 5 6 6]
Sorted x (out of place): [2 2 3 5 6 6 6 9 9 9]
x after sorting: [9 9 2 9 6 2 3 5 6 6]


In [59]:
X = np.random.randint(1,11,size=(5,5))

print('Original X = \n', X)

print('X with sorted columns :\n', np.sort(X, axis = 0))

print('X with sorted rows :\n', np.sort(X, axis = 1))

Original X = 
 [[ 3  1 10  9  1]
 [10 10  5  5  1]
 [10  8  4  3  4]
 [ 4  4 10  6  6]
 [ 3 10 10 10  6]]
X with sorted columns :
 [[ 3  1  4  3  1]
 [ 3  4  5  5  1]
 [ 4  8 10  6  4]
 [10 10 10  9  6]
 [10 10 10 10  6]]
X with sorted rows :
 [[ 1  1  3  9 10]
 [ 1  5  5 10 10]
 [ 3  4  4  8 10]
 [ 4  4  6  6 10]
 [ 3  6 10 10 10]]


# Arthmetic Operations and Broadcasting

In [60]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

print('x = ', x)

print('y = ', y)

print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x =  [1 2 3 4]
y =  [5.5 6.5 7.5 8.5]
x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


In [61]:
x = np.array([1,2,3,4])

print('x = ', x)

print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2

x =  [1 2 3 4]
EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


In [62]:
X = np.array([[1,2], [3,4]])

print('X = \n', X)

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

X = 
 [[1 2]
 [3 4]]
Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [63]:
X = np.array([[1,2], [3,4]])

print('X = \n', X)

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

X = 
 [[1 2]
 [3 4]]
3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In [64]:
x = np.array([1,2,3])

Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

Z = np.array([1,2,3]).reshape(3,1)

print('x = ', x)

print('Y = \n', Y)

print('Z = \n', Z)

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)

x =  [1 2 3]
Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Z = 
 [[1]
 [2]
 [3]]
x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
