# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2) #start end stepsize

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.eye(4)       #this is identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.70741764, 0.83770719, 0.99829027, 0.21447456, 0.51483995])

In [14]:
np.random.rand(3,3)

array([[0.51548188, 0.07000312, 0.04659261],
       [0.39294048, 0.01189374, 0.30741031],
       [0.20027998, 0.7042468 , 0.51565523]])

In [15]:
np.random.randn(2)

array([1.14451569, 0.79950885])

In [16]:
np.random.randint(1,10,5) #if want unique than use set

array([4, 2, 3, 9, 9])

In [17]:
ranarr = np.random.randint(0,50,10)

In [18]:
ranarr

array([31, 33,  5, 34, 45,  8, 15, 30, 13,  3])

In [19]:
arr = [1,2,3,4,5,7,6,8,9,10,11,12,15,1,3]
arr = np.array(arr)
arr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10],
       [11, 12, 15,  1,  3]])

In [20]:
ranarr.max()

45

In [21]:
ranarr.argmax()

4

In [22]:
ranarr.argmin()

9

In [23]:
arr = arr.reshape(3,5)

In [24]:
arr.shape

(3, 5)

In [25]:
arr.dtype

dtype('int32')

In [26]:
from numpy.random import randint

In [27]:
randint(2,10)

3

# Numpy Indexing and Selection

In [28]:
import numpy as np

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[4]

4

In [33]:
arr[1:5]

array([1, 2, 3, 4])

In [34]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[0:5]=100

In [36]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
slice_of_arr = arr[1:5]

In [40]:
slice_of_arr

array([1, 2, 3, 4])

In [41]:
slice_of_arr[:] =99

In [42]:
slice_of_arr

array([99, 99, 99, 99])

In [43]:
arr  #Most Important Point

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr2 = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [48]:
arr2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr2[2][1]

40

In [51]:
arr2[1,2]

30

In [53]:
arr2[:2,1:]

array([[10, 15],
       [25, 30]])

In [54]:
arr2[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [55]:
arr = np.arange(1,11)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bool_arr = arr > 5

In [58]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [61]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [62]:
arr[arr<3]

array([1, 2])

In [63]:
arr2 = np.arange(50).reshape(5,10)

In [64]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Numpy Operations

In [65]:
import numpy as np

In [66]:
arr=np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [72]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [73]:
1/arr

C:\Users\Raghav\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [74]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# Universal Array Function

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [76]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [77]:
np.max(arr)

10

In [78]:
np.min(arr)

0

In [79]:
np.log(arr)

C:\Users\Raghav\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [80]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])